// for login
export const LOGINLOADING = "LOGINLOADING"
export const LOGINSUCCESS = "LOGINSUCCESS"
export const LOGINFAILURE = "LOGINFAILURE"


// for logout
export const LOGOUTLOADING = "LOGOUTLOADING"
export const LOGOUTSUCCESS = "LOGOUTSUCCESS"
export const LOGOUTFAILURE = "LOGOUTFAILURE"


